### ISSUE TITLE
adinehbook should understand the pattern (به اهتمام)

### ISSUE THREAD

**Issue by Huji** [5j9/citer#10]
In an example like [this](https://tools.wmflabs.org/yadfa/citer.fcgi?input_type=url-doi-isbn&user_input=9649113150) the script fails to identify the author because his name is followed by "(به اهتمام)". The script seems to already tackle other similar phrases like "(مترجم)" or "(ویراستار)" and it would be great if it could tackle this one too.

**Comment by Huji** [comment]
FYI, yadfa has stopped working since this was patched. The link in this issue is not working anymore.

**Comment by 5j9** [comment]
@Huji, thanks for the heads-up. I think it's a trusty-to-stretch migration issue and I'm not sure yet what was causing it since there is no sign of any errors in the logs. It could be due the old trusty webservice not being completely shutdown which I have now stopped. The webservice is working fine at this moment.
