### ISSUE TITLE
support for wayback machine

### ISSUE THREAD

**Issue by fgnievinski** [5j9/citer#26]
thanks a lot for your tool.

it seems that links to archive.org are not supported?

for example:

https://web.archive.org/web/20110101182236/http://www.metsul.com/secoes/visualiza.php?cod_subsecao=32&cod_texto=208

**Comment by 5j9** [comment]
If you're using the bookmarklet, this is a known issue. The bookmarklet does not work on archive.org because they've changed the internal `open` function of the page so that every link that one clicks on will be opened in archive.org. This means that the bookmarklet is not able to open Citer's page when called on an archive.org webpage.

I have not been able to find any way around this, so I guess we'll just have use Citer directly in this case. :(

**Comment by fgnievinski** [comment]
Disabling the Chrome extension "Save to Facebook" resolved the issue, thanks.

Background: https://en.wikipedia.org/wiki/Bookmarklet
