### ISSUE TITLE
not working on ACM DOIs

### ISSUE THREAD

**Issue by Wingman4l7** [5j9/citer#37]
Only have tested this one, might work on others?
https://dl.acm.org/doi/10.5555/3157382.3157535

**Comment by 5j9** [comment]
The reason it is not working is that `10.5555/3157382.3157535` is not registered on https://www.doi.org/ . Citer uses doi.org for resolving DOIs. I'm closing this one as wontfix because I don't think there is anything I can do here. However, I might reconsider if someone introduces me to a better DOI resolving method that can handle this particular doi.
